spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hackathon
    username: postgres
    password: postgres
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

      hibernate:
        ddl-auto: create
server:
  port: 9095